/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */



/**
 *
 * @author Hamza Khan Niaz
 */
public class MenuCalculator extends javax.swing.JFrame {

    /**
     * Creates new form MenuCalculator
     */
    public MenuCalculator() {
        initComponents();
        
        buttonGroup_Collection.add(rdoDelivery);
        buttonGroup_Collection.add(rdoCollection);
        
    }

    final int BEEFBURGER = 5;
    final double CHEESEBURGER = 5.50;
    final int VEGGIEPIZZA = 10;
    final int MEATFEASTPIZZA = 13;
    final double FRIES = 3.50;
    final double SALAD = 2.50;
    final int GARLICBREAD = 4;
    final int WEDGES = 5;
    final double COKE = 2.50;
    final double WATER = 1.80;
    final int COLLECTION = 0;
    final int DELIVERY = 5;
    final double VAT = 20;
    
    int Fries = 0;
    int Salad = 0;
    int GarlicBread = 0;
    int Wedges = 0;
    int BeefBurger = 0;
    int CheeseBurger = 0;
    int VeggiePizza = 0;
    int MeatFeastPizza = 0;
    int Coke = 0;
    int Water = 0;
    
    int OrderPrice = 0;
    int miles = 0;
    int DeliverySubTotal = 0;
    int OrderSubTotal = 0;
    double Delivery = 0;
    double vatTotal = 0;
    double netSubTotal = 0;
    double finalTotal = 0;
    String message;
     
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup_Collection = new javax.swing.ButtonGroup();
        rdoBeefBurger = new javax.swing.JRadioButton();
        rdoWater = new javax.swing.JRadioButton();
        rdoCheeseBurger = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        rdoVeggiePizza = new javax.swing.JRadioButton();
        txtDelivery = new javax.swing.JTextField();
        rdoMeatFeastPizza = new javax.swing.JRadioButton();
        rdoCollection = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtQuote1 = new javax.swing.JTextArea();
        rdoFries = new javax.swing.JRadioButton();
        rdoSalad = new javax.swing.JRadioButton();
        rdoGarlicBread = new javax.swing.JRadioButton();
        rdoWedges = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        rdoDelivery = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        rdoCoke = new javax.swing.JRadioButton();
        btnClear = new javax.swing.JButton();
        btnCalculate = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtWedges = new javax.swing.JTextField();
        txtSalad = new javax.swing.JTextField();
        txtGarlicBread = new javax.swing.JTextField();
        txtBeefBurger = new javax.swing.JTextField();
        txtFries = new javax.swing.JTextField();
        txtCheeseBurger = new javax.swing.JTextField();
        txtVeggiePizza = new javax.swing.JTextField();
        txtMeatFeastPizza = new javax.swing.JTextField();
        txtCoke = new javax.swing.JTextField();
        txtWater = new javax.swing.JTextField();
        txtEmployeeResult = new javax.swing.JTextField();
        txtCustomerResult = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        Employeebtn = new javax.swing.JButton();
        Customerbtn = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setResizable(false);

        rdoBeefBurger.setText("Beef Burger   £5.00");
        rdoBeefBurger.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        rdoBeefBurger.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        rdoWater.setText("Water £1.80");
        rdoWater.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        rdoWater.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        rdoCheeseBurger.setText("Cheese Burger £5.50");
        rdoCheeseBurger.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        rdoCheeseBurger.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel5.setText("4. Delivery or Collection");

        rdoVeggiePizza.setText("Veggie Pizza £10.00");
        rdoVeggiePizza.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        rdoVeggiePizza.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        txtDelivery.setText("0");

        rdoMeatFeastPizza.setText("Meat Feast Pizza  £13.00");
        rdoMeatFeastPizza.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        rdoMeatFeastPizza.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        rdoCollection.setText("Collection ");
        rdoCollection.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        rdoCollection.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("2. Main");

        txtQuote1.setEditable(false);
        txtQuote1.setColumns(20);
        txtQuote1.setFont(new java.awt.Font("Courier New", 0, 13)); // NOI18N
        txtQuote1.setRows(5);
        txtQuote1.setToolTipText("");
        jScrollPane2.setViewportView(txtQuote1);

        rdoFries.setText("Fries £3.50");
        rdoFries.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        rdoFries.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        rdoSalad.setText("Salad £2.50");
        rdoSalad.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        rdoSalad.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        rdoGarlicBread.setText("Garlic Bread £4.00");
        rdoGarlicBread.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        rdoGarlicBread.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        rdoWedges.setText("Wedges £5.00");
        rdoWedges.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        rdoWedges.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel1.setFont(new java.awt.Font("Adobe Garamond Pro", 1, 36)); // NOI18N
        jLabel1.setText("Delhi Enterprises");
        jLabel1.setToolTipText("");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("3. Drinks");

        rdoDelivery.setText("Delivery £5 a mile");
        rdoDelivery.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        rdoDelivery.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        rdoDelivery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoDeliveryActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("1. Starters");

        rdoCoke.setText("Coke £2.50 ");
        rdoCoke.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        rdoCoke.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnCalculate.setText("Calculate");
        btnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateActionPerformed(evt);
            }
        });

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        jLabel6.setText("Our fabulous and finest Indian dishes and food, visit us today!");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Welcom to Delhi Enterprises, we are not the only but we are the best. ");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("CONTACT:");

        jLabel11.setText("Telephone: 020 8858 6780");

        jLabel12.setText("10 Greenwich Church Street");

        jLabel13.setText("London SE10 97J");

        txtWedges.setText("0");
        txtWedges.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWedgesActionPerformed(evt);
            }
        });

        txtSalad.setText("0");

        txtGarlicBread.setText("0");

        txtBeefBurger.setText("0");

        txtFries.setText("0");

        txtCheeseBurger.setText("0");

        txtVeggiePizza.setText("0");

        txtMeatFeastPizza.setText("0");

        txtCoke.setText("0");

        txtWater.setText("0");

        txtEmployeeResult.setEditable(false);
        txtEmployeeResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmployeeResultActionPerformed(evt);
            }
        });

        txtCustomerResult.setEditable(false);
        txtCustomerResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustomerResultActionPerformed(evt);
            }
        });

        jLabel14.setText("Staff Name:");

        jLabel15.setText("Customer Name:");

        Employeebtn.setText("Staff");
        Employeebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmployeebtnActionPerformed(evt);
            }
        });

        Customerbtn.setText("Customer");
        Customerbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerbtnActionPerformed(evt);
            }
        });

        jLabel16.setText("Staff and Customer Details:");

        jButton1.setText("Help");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(119, 119, 119)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(87, 87, 87)
                                .addComponent(jLabel6))
                            .addComponent(jLabel7)
                            .addComponent(jButton1))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addComponent(rdoGarlicBread)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(rdoFries)
                                                            .addComponent(rdoWedges)
                                                            .addComponent(rdoSalad))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtSalad, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtGarlicBread, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtWedges, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtFries, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(36, 36, 36)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel3)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addComponent(rdoVeggiePizza)
                                                    .addGap(32, 32, 32)
                                                    .addComponent(txtVeggiePizza, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addComponent(rdoCheeseBurger)
                                                    .addGap(26, 26, 26)
                                                    .addComponent(txtCheeseBurger, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addComponent(rdoBeefBurger)
                                                    .addGap(34, 34, 34)
                                                    .addComponent(txtBeefBurger, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(rdoMeatFeastPizza)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(txtMeatFeastPizza, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(rdoWater)
                                            .addComponent(rdoCoke))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtCoke, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtWater, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel5)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(3, 3, 3)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(rdoCollection)
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addComponent(rdoDelivery)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                            .addComponent(txtDelivery, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                            .addGap(161, 161, 161)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(Employeebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(32, 32, 32)
                                                    .addComponent(Customerbtn))
                                                .addComponent(jLabel16)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel13)
                                                .addComponent(jLabel11)
                                                .addComponent(jLabel12)
                                                .addComponent(jLabel10))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(btnCalculate)
                                                    .addGap(189, 189, 189)
                                                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel14))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtEmployeeResult)
                                    .addComponent(txtCustomerResult, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtBeefBurger, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(rdoFries)
                                        .addComponent(rdoBeefBurger)
                                        .addComponent(rdoCoke)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(rdoCheeseBurger)
                                        .addComponent(txtCheeseBurger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(rdoSalad))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtVeggiePizza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rdoVeggiePizza, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rdoGarlicBread))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(rdoWedges)
                                            .addComponent(txtMeatFeastPizza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rdoMeatFeastPizza))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtFries, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSalad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtGarlicBread, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)
                                .addComponent(txtWedges, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(rdoWater)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtCoke, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtWater, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rdoDelivery)
                            .addComponent(txtDelivery, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdoCollection)
                        .addGap(190, 190, 190))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Customerbtn)
                            .addComponent(Employeebtn))
                        .addGap(11, 11, 11)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnClear)
                    .addComponent(btnCalculate))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmployeeResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCustomerResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnExit)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdoDeliveryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoDeliveryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoDeliveryActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        
        txtQuote1.setText("");
        txtDelivery.setText("0");
        txtFries.setText("0");
        txtWedges.setText("0");
        txtSalad.setText("0");
        txtGarlicBread.setText("0");
        txtBeefBurger.setText("0");
        txtCheeseBurger.setText("0");
        txtMeatFeastPizza.setText("0");
        txtVeggiePizza.setText("0");
        txtWater.setText("0");
        txtCoke.setText("0");
        

        DeliverySubTotal = 0;
        OrderSubTotal = 0;
        OrderPrice = 0;

        rdoBeefBurger.setSelected(false);
        rdoCheeseBurger.setSelected(false);
        rdoVeggiePizza.setSelected(false);
        rdoMeatFeastPizza.setSelected(false);
        rdoFries.setSelected(false);
        rdoSalad.setSelected(false);
        rdoGarlicBread.setSelected(false);
        rdoWedges.setSelected(false);
        rdoCoke.setSelected(false);
        rdoWater.setSelected(false);
        rdoDelivery.setSelected(false);
        rdoCollection.setSelected(false);
        
        txtCustomerResult.setText("");
        txtEmployeeResult.setText("");
        
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed
        
        DeliverySubTotal =0;
        OrderPrice = 0;

        OrderSubTotal = 0;
        vatTotal = 0;
        netSubTotal = 0;
        finalTotal = 0;

        miles = Integer.parseInt(txtDelivery.getText());
        Fries = Integer.parseInt(txtFries.getText());
        Salad = Integer.parseInt(txtSalad.getText());
        Wedges = Integer.parseInt(txtWedges.getText());
        GarlicBread = Integer.parseInt(txtGarlicBread.getText());
        BeefBurger = Integer.parseInt(txtBeefBurger.getText());
        CheeseBurger = Integer.parseInt(txtCheeseBurger.getText());
        VeggiePizza = Integer.parseInt(txtVeggiePizza.getText());
        MeatFeastPizza = Integer.parseInt(txtMeatFeastPizza.getText());
        Coke = Integer.parseInt(txtCoke.getText());
        Water = Integer.parseInt(txtWater.getText());
        

        message = "Delhi Enterprises \n";
        message += "Total order price\n";

        Delivery = DELIVERY * miles;
        message += "-------- Food Order --------\n";

        //Standar burger
        if (rdoBeefBurger.isSelected())
        {
            BeefBurger = Integer.parseInt(txtBeefBurger.getText().toString());
            OrderSubTotal += BEEFBURGER * BeefBurger;
            message +=   "Food @ £" + BEEFBURGER + " per Beef Burger = £" + OrderSubTotal + "\n";
        }
        
        //Cheese Pizza
        if (rdoVeggiePizza.isSelected())
        {
            VeggiePizza = Integer.parseInt(txtVeggiePizza.getText().toString());
            OrderSubTotal += VEGGIEPIZZA * VeggiePizza;
            message +=   "Food @ £" + VEGGIEPIZZA + " per Veggie Pizza = £" + OrderSubTotal + "\n";         
        }
        
        //Cheeze Burger
        if (rdoCheeseBurger.isSelected())
        {
            CheeseBurger = Integer.parseInt(txtCheeseBurger.getText().toString());
            OrderSubTotal += CHEESEBURGER * CheeseBurger;
            message +=   "Food @ £" + CHEESEBURGER + " per Cheese Burger = £" + OrderSubTotal + "\n";
        }
        
        //Pepporoni Pizza
        if (rdoMeatFeastPizza.isSelected())
        {
            MeatFeastPizza = Integer.parseInt(txtMeatFeastPizza.getText().toString());
            OrderSubTotal += MEATFEASTPIZZA * MeatFeastPizza;
            message +=   "Food @ £" + MEATFEASTPIZZA + " per Pepporoni Pizza = £" + OrderSubTotal + "\n";
        }
        
        //Salad
        if (rdoSalad.isSelected())
        {
            Salad = Integer.parseInt(txtSalad.getText().toString());
            OrderSubTotal += SALAD * Salad;
            message +=   "Food @ £" + SALAD + " per Salad = £" + OrderSubTotal + "\n"; 
        }
        
        //Fries
        if (rdoFries.isSelected())
        {
            Fries = Integer.parseInt(txtFries.getText().toString());
            OrderSubTotal += FRIES * Fries;
            message +=   "Food @ £" + FRIES + " per Fries = £" + OrderSubTotal + "\n";    
        }
        
        //Garlic Bread
        if (rdoGarlicBread.isSelected())
        {
            GarlicBread = Integer.parseInt(txtGarlicBread.getText().toString());
            OrderSubTotal += GARLICBREAD * GarlicBread;
            message +=   "Food @ £" + GARLICBREAD + " per Garlic Bread = £" + OrderSubTotal + "\n";
        }
        
        //Wedges
        if (rdoWedges.isSelected())
        {
            Wedges = Integer.parseInt(txtWedges.getText().toString());
            OrderSubTotal += WEDGES * Wedges;
            message +=   "Food @ £" + WEDGES + " per Wedges = £" + OrderSubTotal + "\n";
        }
        
        //Garlic Bread
        if (rdoCoke.isSelected())
        { 
            Coke = Integer.parseInt(txtCoke.getText().toString());
            OrderSubTotal += COKE * Coke;
            message +=   "Food @ £" + COKE + " per Fizzy Drink = £" + OrderSubTotal + "\n";  
        }
        
        //Garlic Bread
        if (rdoWater.isSelected())
        {
            Water = Integer.parseInt(txtWater.getText().toString());
            OrderSubTotal += WATER * Water;
            message +=   "Food @ £" + WATER + " per Water = £" + OrderSubTotal + "\n";
        }
        message += "------Delivery & Collection------\n";
            
        
        //Delivery
        if(rdoDelivery.isSelected())
        {
            miles = Integer.parseInt(txtDelivery.getText().toString());
            
            DeliverySubTotal = DELIVERY * miles;
            
            message += miles + " miles @ £" + DELIVERY + " per mile = £" + DeliverySubTotal + "\n";
        
        }
        
        //Collection
        if(rdoCollection.isSelected())
        {
                message += "Collection charges: £ 0";
        }
        
        
        netSubTotal = DeliverySubTotal + OrderSubTotal;

        message += "\n----- Final Costings ------\n";
        message += "Sub total: £ " 
    
         + netSubTotal + "\n";

        vatTotal = (VAT/100 * netSubTotal);
        message += "VAT: £ " + String.format( "%.2f", vatTotal) + "\n";

        finalTotal = vatTotal + netSubTotal;

        message += "-------------------------"
                + "\nFinal total: £ " + finalTotal + "\n";
        
        message += "-------------------------";

    
        
        txtQuote1.setText(message);

    }//GEN-LAST:event_btnCalculateActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void txtWedgesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWedgesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWedgesActionPerformed

    private void txtEmployeeResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmployeeResultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmployeeResultActionPerformed

    private void txtCustomerResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustomerResultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustomerResultActionPerformed

    private void EmployeebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmployeebtnActionPerformed
        // TODO add your handling code here:
        Staff ST = new Staff();
        ST.setVisible(true);
    }//GEN-LAST:event_EmployeebtnActionPerformed

    private void CustomerbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerbtnActionPerformed
        // TODO add your handling code here:
        Customer CUS = new Customer();
        CUS.setVisible(true);
    }//GEN-LAST:event_CustomerbtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        Help HLP = new Help();
        HLP.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuCalculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Customerbtn;
    private javax.swing.JButton Employeebtn;
    private javax.swing.JButton btnCalculate;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnExit;
    private javax.swing.ButtonGroup buttonGroup_Collection;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton rdoBeefBurger;
    private javax.swing.JRadioButton rdoCheeseBurger;
    private javax.swing.JRadioButton rdoCoke;
    private javax.swing.JRadioButton rdoCollection;
    private javax.swing.JRadioButton rdoDelivery;
    private javax.swing.JRadioButton rdoFries;
    private javax.swing.JRadioButton rdoGarlicBread;
    private javax.swing.JRadioButton rdoMeatFeastPizza;
    private javax.swing.JRadioButton rdoSalad;
    private javax.swing.JRadioButton rdoVeggiePizza;
    private javax.swing.JRadioButton rdoWater;
    private javax.swing.JRadioButton rdoWedges;
    private javax.swing.JTextField txtBeefBurger;
    private javax.swing.JTextField txtCheeseBurger;
    private javax.swing.JTextField txtCoke;
    public static javax.swing.JTextField txtCustomerResult;
    private javax.swing.JTextField txtDelivery;
    public static javax.swing.JTextField txtEmployeeResult;
    private javax.swing.JTextField txtFries;
    private javax.swing.JTextField txtGarlicBread;
    private javax.swing.JTextField txtMeatFeastPizza;
    private javax.swing.JTextArea txtQuote1;
    private javax.swing.JTextField txtSalad;
    private javax.swing.JTextField txtVeggiePizza;
    private javax.swing.JTextField txtWater;
    private javax.swing.JTextField txtWedges;
    // End of variables declaration//GEN-END:variables
}
